### ISSUE TITLE
Fix kernel version conflict with OFED drivers

### ISSUE THREAD

**Issue by jcamposeco** [microsoft/CBL-Mariner-SmartNIC#6]

**Comment by rlmenge** [comment]
Just curious, as a part of this issue, do you plan to update the mnlx-ofa_kernel.spec? (see https://github.com/microsoft/CBL-Mariner/blob/2.0/SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec#L64)

**Comment by jcamposeco** [comment]
> Just curious, as a part of this issue, do you plan to update the mnlx-ofa_kernel.spec? (see https://github.com/microsoft/CBL-Mariner/blob/2.0/SPECS/mlnx-ofa_kernel/mlnx-ofa_kernel.spec#L64)

I think it might be needed at some point, but i need to get a little bit more details on why de we need to build OFA kernels all the time along with Mariner Base image. Probably more things need to get updated along with OFA like 

https://github.com/microsoft/CBL-Mariner/blob/2.0/SPECS/mlnx-tools/mlnx-tools.spec

I;m not certain this is the right way to keep updating these versions, but i will look into that

**Comment by jcamposeco** [comment]
Resolved in #7
